require("api/modelData.lua")
require("api/shipTemplate.lua")
require("api/entity/spaceobject.lua")
require("api/entity/factioninfo.lua")
require("api/entity/shiptemplatebasedobject.lua")
require("api/entity/playerspaceship.lua")
require("api/entity/cpuship.lua")
require("api/entity/spacestation.lua")

require("api/entity/asteroid.lua")
require("api/entity/mine.lua")
