require("options.lua")
require(lang .. "/factions.lua")

neutral = FactionInfo():setName(neutralFaction)
neutral:setDescription(neutralDescription)
neutral:setGMColor(128, 128, 128)

human = FactionInfo():setName(humanFaction)
human:setDescription(humanDescription)
human:setGMColor(255, 255, 255)

kraylor = FactionInfo():setName(kraylorFaction)
kraylor:setDescription(kraylorDescription)
kraylor:setGMColor(255, 0, 0)
kraylor:setEnemy(human)

arlenians = FactionInfo():setName(arleniansFaction)
arlenians:setDescription(arleniansDescription)
arlenians:setGMColor(255, 128, 0)
arlenians:setEnemy(kraylor)

exuari = FactionInfo():setName(exuariFaction)
exuari:setDescription(exuariDescription)
exuari:setGMColor(255, 0, 128)
exuari:setEnemy(neutral)
exuari:setEnemy(human)
exuari:setEnemy(kraylor)
exuari:setEnemy(arlenians)

GITM = FactionInfo():setName(gitmFaction)
GITM:setDescription(gitmDescription)
GITM:setGMColor(0, 255, 0)
GITM:setEnemy(human)

Hive = FactionInfo():setName(hiveFaction)
Hive:setDescription(hiveDescription)
Hive:setGMColor(128, 255, 0)
Hive:setEnemy(human)
Hive:setEnemy(exuari)
Hive:setEnemy(kraylor)

TSN = FactionInfo():setName(tsnFaction)
TSN:setDescription(tsnDescription)
TSN:setGMColor(255, 255, 128)
TSN:setFriendly(human)
TSN:setEnemy(kraylor)
TSN:setEnemy(exuari)
TSN:setEnemy(arlenians)
TSN:setEnemy(Hive)

USN = FactionInfo():setName(usnFaction)
USN:setDescription(usnDescription)
USN:setGMColor(255, 128, 255)
USN:setFriendly(human)
USN:setEnemy(exuari)
USN:setEnemy(GITM)
USN:setEnemy(Hive)
USN:setEnemy(TSN)

CUF = FactionInfo():setName(cufFaction)
CUF:setDescription(cufDescription)
CUF:setGMColor(128, 255, 255)
CUF:setFriendly(human)
CUF:setEnemy(exuari)
CUF:setEnemy(kraylor)
CUF:setEnemy(GITM)