-- This code was auto-generated by your application. 
-- Manual changes to this file may cause unexpected behavior in your application. 
-- Manual changes to this file will be overwritten if the code is regenerated. 
lang = "fr_FR"