--[[                  Stations
These are templates for space stations.
----------------------------------------------------------]]

template = ShipTemplate():setName("Small Station"):setModel("space_station_4"):setClass("Station", "Outpost")
template:setPhysics(true, true)
template:setSpeed(0, 0, 0)
template:setSharesEnergyWithDocked(true)
template:setRepairDocked(true)
template:setRestocksScanProbes(true)
template:setDockClasses("Starfighter", "Frigate", "Corvette")
template:setDescription([[Stations of this size are often used as research outposts, listening stations, and security checkpoints. Crews turn over frequently in a small station's cramped accommodatations, but they are small enough to look like ships on many long-range sensors, and organized raiders sometimes take advantage of this by placing small stations in nebulae to serve as raiding bases. They are lightly shielded and vulnerable to swarming assaults.]])
template:setHull(150)
template:setShields(300)
template:setRadarTrace("radartrace_smallstation.png")

template = ShipTemplate():setName("Medium Station"):setModel("space_station_3"):setClass("Station", "Depot")
template:setPhysics(true, true)
template:setSpeed(0, 0, 0)
template:setSharesEnergyWithDocked(true)
template:setRepairDocked(true)
template:setRestocksScanProbes(true)
template:setDockClasses("Starfighter", "Frigate", "Corvette")
template:setDescription([[Large enough to accommodate small crews for extended periods of times, stations of this size are often trading posts, refuelling bases, mining operations, and forward military bases. While their shields are strong, concerted attacks by many ships can bring them down quickly.]])
template:setHull(400)
template:setShields(800)
template:setRadarTrace("radartrace_mediumstation.png")

template = ShipTemplate():setName("Large Station"):setModel("space_station_2"):setClass("Station", "Station")
template:setPhysics(true, true)
template:setSpeed(0, 0, 0)
template:setSharesEnergyWithDocked(true)
template:setRepairDocked(true)
template:setRestocksScanProbes(true)
template:setDockClasses("Starfighter", "Frigate", "Corvette")
template:setDescription([[These spaceborne communities often represent permanent bases in a sector. Stations of this size can be military installations, commercial hubs, deep-space settlements, and small shipyards. Only a concentrated attack can penetrate a large station's shields, and its hull can withstand all but the most powerful weaponry.]])
template:setHull(500)
template:setShields(1000, 1000, 1000)
template:setRadarTrace("radartrace_largestation.png")

template = ShipTemplate():setName("Huge Station"):setModel("space_station_1"):setClass("Station", "Starbase")
template:setPhysics(true, true)
template:setSpeed(0, 0, 0)
template:setSharesEnergyWithDocked(true)
template:setRepairDocked(true)
template:setRestocksScanProbes(true)
template:setDockClasses("Starfighter", "Frigate", "Corvette", "Dreadnaught")
template:setDescription([[The size of a sprawling town, stations at this scale represent a faction's center of spaceborne power in a region. They serve many functions at once and represent an extensive investment of time, money, and labor. A huge station's shields and thick hull can keep it intact long enough for reinforcements to arrive, even when faced with an ongoing siege or massive, perfectly coordinated assault.]])
template:setHull(800)
template:setShields(1200, 1200, 1200, 1200)
template:setRadarTrace("radartrace_hugestation.png")
