-- Jump poi t

-- Fighter
template = ShipTemplate():setName("Comet Class Starfighter"):setClass("Comet", "Starfighter"):setModel("eoc_fighter")
template:setRadarTrace("eoc_starfighter.png")
--             Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 1000.0, 2.0, 10)
template:setHull(100)
template:setShields(100)
template:setSpeed(60, 10, 20)
template:setCombatManeuver(600, 150)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:setCloaking(false)
template:setEnergyStorage(400)
template:setTubes(1, 10.0) -- Amount of torpedo tubes, loading time
template:setTubeDirection(0, 0)
template:setWeaponStorage("Homing", 250)
template:hidden()

-- Starcaller
template = ShipTemplate():setName("Comet Class Scout"):setClass("Comet", "Scout"):setModel("eoc_frigate")
template:setRadarTrace("eoc_scout.png")
--             Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 1500.0, 4.0, 50)
template:setTubes(4, 8.0)
template:setTubeDirection(0, 0)
template:setTubeDirection(1, 0)
template:setTubeDirection(2, 45)
template:setTubeDirection(3,-45)
template:setHull(200)
template:setShields(300, 300)
template:setSpeed(30, 10, 10)
template:setCombatManeuver(300, 50)
template:setJumpDrive(false)
template:setCloaking(false)
template:setEnergyStorage(600)
template:setWeaponStorage("Homing", 250)
template:hidden()

template:setShortRangeRadarRange(10000)
template:setLongRangeRadarRange(100000)

template:setRepairCrewCount(0)
--	(H)oriz, (V)ert	   HC,VC,HS,VS, system    (C)oordinate (S)ize
template:addRoomSystem( 0, 1, 1, 2, "Impulse")
template:addRoomSystem( 1, 0, 2, 1, "RearShield")
template:addRoomSystem( 1, 1, 2, 2, "JumpDrive")
template:addRoomSystem( 1, 3, 2, 1, "FrontShield")
template:addRoomSystem( 3, 0, 2, 1, "Beamweapons")
template:addRoomSystem( 3, 1, 3, 1, "Warp")
template:addRoomSystem( 3, 2, 3, 1, "Reactor")
template:addRoomSystem( 3, 3, 2, 1, "MissileSystem")
template:addRoomSystem( 6, 1, 1, 2, "Maneuver")

-- (H)oriz, (V)ert H, V, true = horizontal
template:addDoor( 1, 1, false)
template:addDoor( 2, 1, true)
template:addDoor( 1, 3, true)
template:addDoor( 3, 2, false)
template:addDoor( 4, 3, true)
template:addDoor( 6, 1, false)
template:addDoor( 4, 2, true)
template:addDoor( 4, 1, true)
template:hidden()


template = ShipTemplate():setName("Luna Class Cargo Carrier"):setClass("Luna", "Carrier"):setModel("space_cruiser_4")
template:setRadarTrace("eoc_carrier.png")
template:setHull(300)
template:setShields(500, 500, 500, 500)
template:setSpeed(40, 5, 5)
template:setBeamWeapon(0, 90, -15, 1200, 8, 6)
template:setBeamWeapon(1, 90,  15, 1200, 8, 6)
template:setTubes(2, 60.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 6)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()

template = ShipTemplate():setName("Aurora Class Landing Craft"):setClass("Aurora", "Landing Craft"):setModel("space_cruiser_4")
template:setRadarTrace("eoc_carrier.png")
template:setHull(300)
template:setShields(500, 500, 500, 500)
template:setSpeed(60, 5, 5)
template:setBeam(0, 30, 0, 1000.0, 2.0, 10)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()


template = ShipTemplate():setName("Aurora Class Explorer"):setClass("Aurora", "Explorer"):setModel("space_cruiser_4")
template:setRadarTrace("eoc_explorer.png")
template:setShields(500, 500, 500, 500)
template:setBeamWeapon(0, 90, 0, 1200, 8, 6)
template:setHull(400)
template:setSpeed(20, 5, 10)
template:setCombatManeuver(400, 250)
template:setTubes(2, 10.0)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setWeaponStorage("Homing", 10)
template:setWeaponStorage("EMP", 3)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()

template = ShipTemplate():setName("Helios Class Corvette"):setClass("Helios", "Corvette"):setModel("eoc_odysseus")
template:setRadarTrace("eoc_corvette.png")
template:setHull(700)
template:setShields(500, 500, 500, 500)
template:setSpeed(15, 5, 5)
template:setBeamWeapon(0, 90, -15, 1200, 8, 6)
template:setBeamWeapon(1, 90,  15, 1200, 8, 6)
template:setTubes(2, 60.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 6)
template:setTubeDirection(0, -1)
template:setTubeDirection(1,  1)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()


template = ShipTemplate():setName("Eclipse Class Frigate"):setClass("Eclipse", "Frigate"):setModel("eoc_frigate")
template:setRadarTrace("eoc_frigate.png")
template:setHull(800)
template:setShields(500, 500, 500, 500, 500, 500, 500, 500)
template:setSpeed(5, 3, 5)
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 60, -10, 2000.0, 8.0, 11)
template:setBeam(1, 60,  10, 2000.0, 8.0, 11)
template:setBeam(2, 60, -20, 1500.0, 8.0, 11)
template:setBeam(3, 60,  20, 1500.0, 8.0, 11)
template:setTubes(2, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 200)
template:setWeaponStorage("EMP", 40)
template:weaponTubeDisallowMissle(1, "EMP")
-- template:setDefaultAI('missilevolley')
template:setTubeDirection(0, 0)
template:setTubeDirection(1, 0)
template:setTubeDirection(2, -45)
template:setTubeDirection(3, 45)
template:setTubeDirection(4, -180)
template:setTubeDirection(5, 180)
template:setWeaponStorage("Homing", 500)
template:setWeaponStorage("EMP", 500)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()

--BattleCruiser
template = ShipTemplate():setName("Stellar Class Battlecruiser"):setClass("Stellar", "Battlecruiser"):setModel("eoc_frigate")
template:setRadarTrace("eoc_battlecruiser.png")
template:setHull(1200)
template:setShields(800, 800, 800, 800, 800, 800, 800, 800)
template:setSpeed(5, 3, 5)
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 60, -10, 2000.0, 8.0, 11)
template:setBeam(1, 60,  10, 2000.0, 8.0, 11)
template:setBeam(2, 60, -20, 1500.0, 8.0, 11)
template:setBeam(3, 60,  20, 1500.0, 8.0, 11)
template:setTubes(2, 10.0)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Homing", 200)
template:setWeaponStorage("EMP", 40)
template:weaponTubeDisallowMissle(1, "EMP")
-- template:setDefaultAI('missilevolley')
template:setTubeDirection(0, 0)
template:setTubeDirection(1, 0)
template:setTubeDirection(2, -45)
template:setTubeDirection(3, 45)
template:setTubeDirection(4, -180)
template:setTubeDirection(5, 180)
template:setWeaponStorage("Homing", 500)
template:setWeaponStorage("EMP", 500)
template:setWarpSpeed(0)
template:setJumpDrive(false)
template:hidden()


-- Space station
template = ShipTemplate():setName("Medium station"):setModel("space_station_2"):setLocaleName(_("Medium Station")):setType("station")
template:setDescription(_([[Large enough to accommodate small crews for extended periods of times, stations of this size are often trading posts, refuelling bases, mining operations, and forward military bases. While their shields are strong, concerted attacks by many ships can bring them down quickly.]]))
template:setRadarTrace("mediumstation.png")
template:setDockClasses("Starfighter")
template:setHull(400)
template:setShields(800)
template:hidden()

-- Jump point
template = ShipTemplate():setName("Jump point"):setLocaleName(_("ship", "Jump point")):setModel("cubesat"):setClass("class", "Jump point")
template:setRadarTrace("satellite.png")
template:setSpeed(0, 0, 0)
template:setHull(400)
template:hidden()


