--[[               Drones
bada bip, bada bop, whaddaya know?
----------------------------------------------------------]]
template = ShipTemplate():setName("L3 Mouse"):setType("drone"):setClass("Drone", "Beamer"):setModel("LaserCorvetteBlue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[beams attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("L3 Cat"):setType("drone"):setClass("Drone", "Swoosher"):setModel("MissileCorvetteBlue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[HVLI attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 4)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)