--[[               Drones
bada bip, bada bop, whaddaya know?
----------------------------------------------------------]]
template = ShipTemplate():setName("L3 Mouse"):setType("drone"):setClass("Drone", "Beamer"):setModel("LaserCorvetteBlue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[beams attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
--                  Arc, Dir, Range, CycleTime, Dmg
template:setBeam(0, 30, 0, 700.0, 4.0, 2)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("L3 Cat"):setType("drone"):setClass("Drone", "Swoosher"):setModel("MissileCorvetteBlue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[HVLI attack drone]])
template:setEnergyStorage(200)
template:setHull(30)
-- template:setShields(20)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
template:setTubes(1, 15.0)
template:setWeaponStorage("HVLI", 4)
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("H9 Owl"):setType("drone"):setClass("Drone", "Swoosher"):setModel("AdlerLongRangeScoutBlue")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Long range scout]])
template:setEnergyStorage(1000)
template:setHull(50)
template:setSpeed(100, 50, 40)
template:setCombatManeuver(400, 250)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)

template = ShipTemplate():setName("M19 Rino"):setType("drone"):setClass("Drone", "Swoosher"):setModel("LindwurmFighterYellow")
template:setHasReactor(false)
template:setRadarTrace("radar_fighter.png")
template:setDescription([[Mine layer]])
template:setEnergyStorage(300)
template:setHull(150)
template:setSpeed(40, 50, 20)
template:setCombatManeuver(400, 250)
template:setTubes(1, 15.0)
template:setWeaponStorage("Mine", 1)
template:setDefaultAI('fighter')
template:setJumpDrive(false)
template:setWarpSpeed(-1)
template:setRepairCrewCount(0)